### PR TITLE
fix(positive suite): API-27884 - add await to async function calls

### PR DESCRIPTION
**Pull request by christineyost**
This change awaits calls to `validateObjectAgainstSchema()` and makes every function that calls `validateObjectAgainstSchema()` async

### CODE REVIEW

**Review by stevelong00 — COMMENTED** [review]
I found a few additional places where .validate() is called without an await:

\src\suites\positive\conductors\request-validation-conductor.ts
line 27

\test\suites\positive\validation\parameter-schema-validator.test.ts
lines 33, 71, 104, 128, 159, 191, 213, 241, 251

**Comment by christineyost** [comment]
@stevelong00 yes, the calls in request-validation-conductor.ts and parameter-schema-validator.test.ts are calling `ParameterSchemaValidator.performValidation()` which is not actually async which is why it is working without the `await`, so I didn't add it in. However maybe we should add it in since the function is already marked async even though its not?

**Comment by stevelong00** [comment]
> @stevelong00 yes, the calls in request-validation-conductor.ts and parameter-schema-validator.test.ts are calling `ParameterSchemaValidator.performValidation()` which is not actually async which is why it is working without the `await`, so I didn't add it in. However maybe we should add it in since the function is already marked async even though its not?

As I understand it, all functions marked async return a promise.  When called without await the result of the promise is ignored.  If this is correct, we should always be using await or maybe the more verbose promise syntax instead.

I'm not 100% sure though, will need to check docs.  I found this because my IDE (Webstorm) flagged that line in request-validation-conductor.ts

**Comment by christineyost** [comment]
I did a bit of reading and found the following [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)
```
The body of an async function can be thought of as being split by zero or more await expressions. Top-level code, up to and including the first await expression (if there is one), is run synchronously. In this way, an async function without an await expression will run synchronously. If there is an await expression inside the function body, however, the async function will always complete asynchronously.
```
I think that's why things seem to currently be working without the extra awaits you mentioned... even though an async function is being called, there is no await so the function is run synchronously. The Promise being returned is not a problem, because we're expecting void to be returned, so we don't do anything with the return value.

However this doesn't seem like functionality we want to be taking advantage of... we want the function to be executed synchronously and it's marked as an async function so I think it will be best to await it when it's called. I'll add in the extra awaits.

**Pull request merged**
