### PR TITLE
API-19697/  add cli parameter for specific suites

### PR DESCRIPTION
**Pull request by mheusgit**
- Added optional id parameter to suites and suites batch

### CODE REVIEW

**Review by dsteeve — COMMENTED** [review]
this all looks correct, but we should probably update the ReadMe as well.

**Comment by mheusgit** [comment]
PR should be good to go

**Review by stevelong00 — DISMISSED** [review]
Very nice!

**Comment by christineyost** [comment]
Looks good!

The only thing I noticed is when running from command line with a suiteId that doesn't exist (`./bin/run suites <PATH> -i doesntexist -a <KEY>`) the output isn't quite right:

```
test: Skipped - Unable to find suite with ID doesntexist
test: Succeeded

```

We end up with an extra successful test. It looks like changing the `getSuitesResults()` method in `loast.ts` where `results` is defined fixes this issue. `let results: OperationResult[] = [];` should be `let results: OperationResult[] | undefined;` instead. This way `results` is like `errorMsg`. If `errorMsg` is present, `results` will be undefined, and if `results` is present `errorMsg` will be present.

**Review by christineyost — APPROVED** [review]
Looks good!

**Pull request merged**
