### PR TITLE
API-5542 typeerror for forms api

### PR DESCRIPTION
**Pull request by michaelkimball**
[API-5542](https://vajira.max.gov/browse/API-5542)

Add schema to findFormByFormName parameter to fix parameter issue﻿

### CODE REVIEW

**Review by alexandervalencia — APPROVED** [review]
LGTM 🚀

**Comment by RockslideJr** [comment]
It might benefit us to update the code to spit out a validation failure when this error happens, since we won't be able to control user's oas files

**Comment by christineyost** [comment]
Agree with John. We shouldn't be responsible for manually parsing the OAS when there's a TypeError

**Comment by michaelkimball** [comment]
> It might benefit us to update the code to spit out a validation failure when this error happens, since we won't be able to control user's oas files

The error shows up clearly. It only showed me TypeError before deleting the `lib` folder and rebuilding with `npm run build`

**Review by RockslideJr — APPROVED** [review]

**Pull request merged**
