### PR TITLE
API-27122/  create new suite in loast  lighthouse api standards 2

### PR DESCRIPTION
**Pull request by mheusgit**
- Implemented support for multiple Spectral rulesets/suites.  This required updating the SuiteFactory and RuleSetValidator to be more generic 
- Added lighthouseAPIStandards.yaml ruleset
- Renamed ruleset.yaml to oas-ruleset.yaml due to there being multiple rulesets now.  Renamed oas-ruleset & OASRuleset folders/classes to just "ruleset" since these assets are now shared
- Refactored naming convention tied to rulesets so custom rulesets can be tracked in LOAST without requiring code changes every time a new rule is added.  This required original ruleset updates to follow new convention.
- Added a Jest script that automatically generates test based on provided rulesets and OAS fixtures

### CODE REVIEW

**Review by christineyost — COMMENTED** [review]
Changes look good to me. I was able to run the new ruleset suite locally.

I have a couple thoughts:
1. I think we should be consistent with naming conventions for LOAST suites. So far we have `positive` and `oas-ruleset`. Should this new suite be called `lighthouse-api-standards` instead of `lighthouseAPIStandards` or should we change `oas-ruleset` to be camel case?
2. I think this testing approach seems good, but we'll end up with a lot of OAS fixtures as new rules/rulesets are added. What are the pros/cons of this approach vs maybe two OAS fixtures per ruleset, where one OAS passes all rules and one fails all rules?
3. If we use this testing approach, would it make sense to group fixtures by ruleset instead of having them in one directory all together? Right now it's hard to know which rules are for which ruleset

**Comment by mheusgit** [comment]
Test mocks require changes from the recent TS updates

**Comment by mheusgit** [comment]
@christineyost 

1. Naming of the file matching the suite name provided by Cassowary.  Pretty much anything could be used as long as you keep in mind it will affect how the suite is called by command line or by direct module usage.  If you switch away from 'oas-ruleset' that will affect the way it is called as well.
2. 
Pro - Allows new rules to be added without requiring new code or Jest logic to support it.  Also allows high degree of flexibility regarding testing rules since multiple rule failures scenarios can be tested in a single file.  
 
Cons - Adding a new suite requires a rulefile, two fixtures, and a setup.json update at minimum to get it in place.  I'd prefer a single file change but that is impractical at this point.  

I thought about using a single OAS for a rule set but lower level failures will be concealed by higher level failures.  For example: If a rule checks for at least method for a path, you will never see that failure if a OAS does not even have any paths.  That lack of paths reports an error that proceeds the method check.

3. Not defining the ruleset tied to the fixture is a pretty nice feature since rulesets may include the same rules.

**Comment by mheusgit** [comment]
Going to recreate this PR branch is too old

**Comment by mheusgit** [comment]
Moved to https://github.com/department-of-veterans-affairs/lighthouse-oas-tests/pull/144

**Pull request closed without merging**
