### PR TITLE
Api 12438/request body

### PR DESCRIPTION
**Pull request by stevelong00**
API-12438 Update LOAST to send a request body along with an operation request

* feat: create example request body for each OASOperation
* fix(requestbodyfactory): check if requestbody is required before building one
* feat: send example request body to swagger-js execute method
* feat: validate request body
* fix(InvalidRequestBodyContent): added missing file to commit
* fix(oas-schema.test.ts): updated test to include the new requestBody
* fix(positive.test.ts): updated test to include the new requestBody
* fix: reapplied some renaming lost in the last merge
* fix: updated some tests that broke in the last merge
* fix: applied additional renaming for consistency
* feat: added unit tests for request body
* fix: renamed a few variables to be more descriptive
* fix: resolved a linter error
* feat: added request body info to readme
* fix: addressed feedback from pull request

  * moved request body validation logic into a new validator class

  * removed validation check 'Content Object contains more than one entry,' this is not a problem for request body content

### CODE REVIEW

**Review by mheusgit — COMMENTED** [review]
Looks good to me

**Review by christineyost — COMMENTED** [review]
This is looking really good to me!

I think one of these request body validations is not needed - commented on this specifically.

I also pulled this locally, ran the Veteran Confirmation OAS through, and got the following output:
```
getVeteranStatus - default: Succeeded
  - Warning: This object is missing non-required properties that were unable to be validated, including middle_name, gender. Path: requestBody -> example. Found 1 time
```
I thought this was a bit unfortunate because not having these properties is a direct consequence of how we built the example request body. I definitely agree that we want to reuse all the rest of the `checkObjectProperties` checks though. Would it be possible to skip that one check for request bodies or does that add too much complexity?

`validateObjectAgainstSchema` looks like it handles a lot of different data types (object, enum, array, etc...). Will a request body always be a JSON object and if so is calling this method that handles other data types confusing? Along these lines I'm wondering if we should introduce a request body validator?

**Comment by stevelong00** [comment]
> I think one of these request body validations is not needed - commented on this specifically.

Agreed, removed.  I also updated the other validation for MissingContentSchemaObject to check all content objects, not just the first.

> I also pulled this locally, ran the Veteran Confirmation OAS through, and got the following output:
>   - Warning: This object is missing non-required properties that were unable to be validated, including middle_name, gender. 

I think the warning is appropriate since we're excluding optional properties.  Should we revisit how we're building the example request body?  If examples are provided for optional properties maybe we ought to be including them?

> `validateObjectAgainstSchema` looks like it handles a lot of different data types (object, enum, array, etc...). Will a request body always be a JSON object and if so is calling this method that handles other data types confusing? Along these lines I'm wondering if we should introduce a request body validator?

I like the idea of moving the request body validation into its own validator class.  This change has been implemented.

A request body can be any MIME type, but it must have a schema defined in the OAS and that's always going to be json.  This method seems appropriate as it handles whatever types are defined in the schema.

Relatedly, and probably worth a new ticket:  I just noticed that an example can be placed on the schema object, should we add support for this?  It could be useful for examples of non-json types like so:

```
content: {
  'image/png': {
    schema: {
      type: 'string',
      format: base64,
      example: 'thisIsAnImageEncodedAsAString',
    },
  },
},
```

**Comment by christineyost** [comment]
The code changes look good!

I discussed with Steve offline, and he is going to create two new tickets, one for handling optional request body properties, and one for handling when an example is defined in the `schema` object.

I did notice we have a problem when running the positive command against the facilities API (and APIs like it) now. The node-fetch library that swagger-client uses to execute a request does not allow request bodies to be sent with a GET or HEAD request. LOAST is currently defaulting to an empty request body `{}` when the OAS operation does not have a request body. Instead of sending an empty request body we need to not send one at all when we don't need to.

**Review by christineyost — APPROVED** [review]
Looks good to me! 🎉

**Pull request merged**
