### PR TITLE
feat: API-26681/doc server and loast  upgrade typescript version

### PR DESCRIPTION
**Pull request by mheusgit**
- Updated TypeScript to v5.1.3
- TS change required Oclif packages to be updated and logic to be migrated.  @oclif/command was migrated to new module @oclif/core v2.8.7.  @oclif/config, @oclif/dev-cli, & cli-ux modules are already included in @oclif/core.  @oclif/plugin-help was updated to v5.2.10
- Updated jest related modules (old version didn't support TS v5+).  jest to v29.5.0 and ts-jest to v29.1.0
- Jest & TS changes allowed removal of ruleset-wrapper.ts and the mocking connected to it in Jest test
- content-type module version bumped to latest
- Added missing dependency references to "@typescript-eslint/eslint-plugin" & "@typescript-eslint/parser".  Same version v2.6.1 is still being applied

### CODE REVIEW

**Comment by mheusgit** [comment]
Ticket needs corresponding DocServer changes confirmed before merging

**Review by dsteeve — APPROVED** [review]
this looks good.  do we need to do a commit with "fix" so that a new version is created?

**Comment by mheusgit** [comment]
First commit says "fixed:"

**Comment by dsteeve** [comment]
> First commit says "fix:"

ok, I think because this defaults to squash and merge, the "feat:" will need to be in PR name to get the minor version to increase.  so I renamed the PR name for this. if you agree with this, then go ahead and merge it.

**Comment by mheusgit** [comment]
Merge delayed due to system access & verification concerns

**Pull request merged**
